#!/bin/bash

NODE_COUNT=${1:-11}
ELDER_COUNT=5
adult_count=$(($NODE_COUNT-$ELDER_COUNT))

source ./droplet-operations
source ./section-operations

setup_doctl
create_elder_droplets
create_adult_droplets $adult_count
echo "$NODE_COUNT Droplets created"
register_hosts
download_node_binary_on_nodes
deploy_elders
deploy_adults
churn

# destroy_all_droplets