#!/bin/bash

source ./droplet-operations
source ./section-operations

setup_doctl
create_elder_droplets
create_adult_droplets
echo "Droplets created"
register_hosts
download_vault_binary_on_nodes
deploy_elders
deploy_adults
churn

# destroy_all_droplets