#!/bin/bash

# https://betterdev.blog/minimal-safe-bash-script-template/
set -Eeuo pipefail
trap cleanup SIGINT SIGTERM ERR EXIT

TESTNET_CHANNEL=$(terraform workspace show)

script_dir=$(cd "$(dirname "${BASH_SOURCE[0]}")" &>/dev/null && pwd -P)

cleanup() {
  trap - SIGINT SIGTERM ERR EXIT
  # script cleanup here
}

socket=${1}

 if [[ -z "${socket}" ]]; then
        echo "A socket addressmust be supplied"
        exit 1
    fi
# rm -rf ${TESTNET_CHANNEL}-connection-infos || true

# mkdir -p ${TESTNET_CHANNEL}-connection-infos
# for ip in $(<${TESTNET_CHANNEL}-ip-list xargs); do
#         rsync root@${ip}:~/.safe/node/node_connection_info.config ${TESTNET_CHANNEL}-connection-infos/${ip}.info &
# done
# wait

# echo "Downloaded connection info files"

# infos=()
# echo "[" > ${TESTNET_CHANNEL}-node_connection_info.config

# for file in $(ls ${TESTNET_CHANNEL}-connection-infos); do
#     infos+=($(cat ${TESTNET_CHANNEL}-connection-infos/$file | head -2 | tail -1))
# done

# we can always insert from line 4 onwards
cat ${TESTNET_CHANNEL}-connection-info | awk -v ip=$socket 'NR==4{print socket}1' > $TMPDIR/temp-config && mv $TMPDIR/temp-config ${TESTNET_CHANNEL}-connection-info

# for info in "${infos[@]}"; do
#         echo "$info," >> ${TESTNET_CHANNEL}-node_connection_info.config
# done

# # replace the last (two) chars which are ,\n
# truncate -s-2 ${TESTNET_CHANNEL}-node_connection_info.config

# echo "]" >> ${TESTNET_CHANNEL}-node_connection_info.config

cleanup