#!/bin/bash

# https://betterdev.blog/minimal-safe-bash-script-template/
set -Eeuo pipefail
trap cleanup SIGINT SIGTERM ERR EXIT

script_dir=$(cd "$(dirname "${BASH_SOURCE[0]}")" &>/dev/null && pwd -P)

cleanup() {
  trap - SIGINT SIGTERM ERR EXIT
  # script cleanup here
}

adult_nodes=()
for ip in $(<adults-ip-list xargs); do
adult_nodes+=(${ip})
done
time=(5m 10m 15m)
hard_coded_contacts=$(cat connection_info)
hard_coded_contacts="[${hard_coded_contacts}]"
while true; do
t=$((RANDOM % 3))
echo "Sleep: ${time[t]}"
sleep ${time[t]}
i=$((RANDOM % 10))
echo "Churning Adults at node ${i}"
ssh root@${adult_nodes[i]} 'pkill sn_node && rm -rf node*'
echo "Sleep 15m"
sleep 15m
ssh root@${adult_nodes[i]} "bash -s" < "$script_dir/../src/start-new-node" "${hard_coded_contacts}" "node_data"
done


cleanup