#!/bin/bash

script_dir=$(cd "$(dirname "${BASH_SOURCE[0]}")" &>/dev/null && pwd -P)
TESTNET_CHANNEL=$(terraform workspace show)

mkdir -p workspace/${TESTNET_CHANNEL}/memory-profiling/

export TESTNET_CHANNEL

parallel --timeout 30 -a workspace/${TESTNET_CHANNEL}/ip-list --colsep ' ' --jobs 5 'name={1}; ip={2}; if [[ -z $name || -z $ip ]]; then echo "$name $ip - Skipping line due to empty name or IP"; else echo "Getting $name heaptrack-data from $ip"; \
  rsync -z root@${ip}:"~/heaptrack*" workspace/${TESTNET_CHANNEL}/memory-profiling/heaptrack.${name}___${ip}/ ; fi'

echo "Logs updated"
