#!/bin/bash

TESTNET_CHANNEL=$(terraform workspace show)

# https://betterdev.blog/minimal-safe-bash-script-template/
set -Eeuo pipefail
trap cleanup SIGINT SIGTERM ERR EXIT

script_dir=$(cd "$(dirname "${BASH_SOURCE[0]}")" &>/dev/null && pwd -P)

cleanup() {
  trap - SIGINT SIGTERM ERR EXIT
  # script cleanup here
}

aws s3 cp "s3://sn-node/testnet_tool/$TESTNET_CHANNEL-ip-list" "workspace/$TESTNET_CHANNEL/ip-list"
./scripts/register_keys.sh

cleanup
