#!/bin/bash

# https://betterdev.blog/minimal-safe-bash-script-template/
set -Eeuo pipefail
trap cleanup SIGINT SIGTERM ERR EXIT

script_dir=$(cd "$(dirname "${BASH_SOURCE[0]}")" &>/dev/null && pwd -P)

cleanup() {
  trap - SIGINT SIGTERM ERR EXIT
  # script cleanup here
}

# rm logs/* || true

mkdir -p logs
for ip in $(<ip-list xargs); do
        rsync --partial root@${ip}:~/nohup.out logs/${ip}.log &
done

echo "Logs updated"

cleanup