#!/bin/bash

# https://betterdev.blog/minimal-safe-bash-script-template/
set -Eeuo pipefail
trap cleanup SIGINT SIGTERM ERR EXIT
#
script_dir=$(cd "$(dirname "${BASH_SOURCE[0]}")" &>/dev/null && pwd -P)
TESTNET_CHANNEL=$(terraform workspace show)

cleanup() {
  trap - SIGINT SIGTERM ERR EXIT
  # script cleanup here
}

mkdir -p memory-profiling/${TESTNET_CHANNEL}

cat ${TESTNET_CHANNEL}-ip-list | while read line; do
  ip=$(echo $line | awk '{print $2}')
  name=$(echo $line | awk '{print $1}')
  echo "$name @ $ip"
  rsync -P root@${ip}:"~/heaptrack*" memory-profiling/${TESTNET_CHANNEL}/heaptrack.${name}___${ip}.zst &
done

cleanup
