#!/bin/bash

TESTNET_CHANNEL=$(terraform workspace show)

# https://betterdev.blog/minimal-safe-bash-script-template/
set -Eeuo pipefail
trap cleanup SIGINT SIGTERM ERR EXIT

script_dir=$(cd "$(dirname "${BASH_SOURCE[0]}")" &>/dev/null && pwd -P)

cleanup() {
  trap - SIGINT SIGTERM ERR EXIT
  # script cleanup here
}

# source "$script_dir/../scripts/droplet-operations"

aws s3 cp "s3://safe-testnet-tool/$TESTNET_CHANNEL-ip-list" "$TESTNET_CHANNEL-ip-list"
aws s3 cp "s3://safe-testnet-tool/$TESTNET_CHANNEL-genesis-ip" "$TESTNET_CHANNEL-genesis-ip"
aws s3 cp "s3://safe-testnet-tool/$TESTNET_CHANNEL-prefix-map" "$TESTNET_CHANNEL-prefix-map"
./scripts/register_keys.sh

cleanup
