#!/bin/bash

# https://betterdev.blog/minimal-safe-bash-script-template/
set -Eeuo pipefail
trap cleanup SIGINT SIGTERM ERR EXIT
#
script_dir=$(cd "$(dirname "${BASH_SOURCE[0]}")" &>/dev/null && pwd -P)
TESTNET_CHANNEL=$(terraform workspace show)
TARGET_NODE_IP=$1

cleanup() {
  trap - SIGINT SIGTERM ERR EXIT
  # script cleanup here
}

mkdir -p memory-profiling/${TESTNET_CHANNEL}

echo "Killing node and getting memory-profiling from $TARGET_NODE_IP"
# ssh root@${TARGET_NODE_IP} 'killall sn_node'
rsync -r -P root@${TARGET_NODE_IP}:"~/heaptrack*" memory-profiling/${TESTNET_CHANNEL}/${TARGET_NODE_IP}/

cleanup