#!/bin/bash

# https://betterdev.blog/minimal-safe-bash-script-template/
set -Eeuo pipefail
trap cleanup SIGINT SIGTERM ERR EXIT

TESTNET_CHANNEL=$(terraform workspace show)
DEFAULT_WORKING_DIR="."
WORKING_DIR="${GITHUB_ACTION_PATH:-$DEFAULT_WORKING_DIR}"

script_dir=$(cd "$(dirname "${BASH_SOURCE[0]}")" &>/dev/null && pwd -P)

cleanup() {
  trap - SIGINT SIGTERM ERR EXIT
  # script cleanup here
}

rm -rf ${WORKING_DIR}/${TESTNET_CHANNEL}-connection-infos || true

mkdir -p ${WORKING_DIR}/${TESTNET_CHANNEL}-connection-infos
for ip in $(<${WORKING_DIR}/${TESTNET_CHANNEL}-ip-list xargs); do
        rsync root@${ip}:~/.safe/node/node_connection_info.config ${WORKING_DIR}/${TESTNET_CHANNEL}-connection-infos/${ip}.info &
done
wait

echo "Downloaded connection info files"

infos=()
echo "[" > ${WORKING_DIR}/${TESTNET_CHANNEL}-node_connection_info.config

for file in $(ls ${WORKING_DIR}/${TESTNET_CHANNEL}-connection-infos); do
    infos+=($(cat ${WORKING_DIR}/${TESTNET_CHANNEL}-connection-infos/$file | head -2 | tail -1))
done

for info in "${infos[@]}"; do
        echo "$info," >> ${WORKING_DIR}/${TESTNET_CHANNEL}-node_connection_info.config
done

# replace the last (two) chars which are ,\n
truncate -s-2 ${WORKING_DIR}/${TESTNET_CHANNEL}-node_connection_info.config

echo "]" >> ${WORKING_DIR}/${TESTNET_CHANNEL}-node_connection_info.config

cleanup