#!/bin/bash

# https://betterdev.blog/minimal-safe-bash-script-template/
set -Eeuo pipefail
trap cleanup SIGINT SIGTERM ERR EXIT

script_dir=$(cd "$(dirname "${BASH_SOURCE[0]}")" &>/dev/null && pwd -P)

cleanup() {
  trap - SIGINT SIGTERM ERR EXIT
  # script cleanup here
}

rm -rf connection-infos || true

mkdir -p connection-infos
for ip in $(<ip-list xargs); do
        rsync root@${ip}:~/.safe/node/node_connection_info.config connection-infos/${ip}.info &
done
wait

echo "Downloaded connection info files"

infos=()
echo "[" > node_connection_info.config

for file in $(ls connection-infos); do
    infos+=($(cat connection-infos/$file | head -2 | tail -1))
done

for info in "${infos[@]}"; do
        echo "$info," >> node_connection_info.config
done

# replace the last (two) chars which are ,\n
truncate -s-2 node_connection_info.config

echo "]" >> node_connection_info.config

cleanup