#!/bin/bash

# https://betterdev.blog/minimal-safe-bash-script-template/
set -Eeuo pipefail
trap cleanup SIGINT SIGTERM ERR EXIT

script_dir=$(cd "$(dirname "${BASH_SOURCE[0]}")" &>/dev/null && pwd -P)

cleanup() {
  trap - SIGINT SIGTERM ERR EXIT
  # script cleanup here
}

mkdir -p logs
elder_count=0
for ip in $(<elders-ip-list xargs); do
        # echo "accessing root@${ip}:/root/node_data/node.stdout"
        #  TODO: this is not overwriting files locally on linux
        rsync --partial root@${ip}:/root/node_data/node.stdout logs/initial-elder-${elder_count}-${ip}.log
        elder_count=$((elder_count + 1))
done

for ip in $(<adults-ip-list xargs); do
        rsync --partial root@${ip}:/root/node_data/node.stdout logs/${ip}.log
done
echo "Logs updated"


cleanup