#!/bin/bash

TESTNET_CHANNEL=$(terraform workspace show)


mkdir -p workspace/${TESTNET_CHANNEL}/logs
cat workspace/${TESTNET_CHANNEL}/ip-list | while read line; do
  ip=$(echo $line | awk '{print $2}')
  name=$(echo $line | awk '{print $1}')
  mkdir -p workspace/${TESTNET_CHANNEL}/logs/${name}___${ip}
  rsync -rz root@${ip}:~/logs/sn_node.log workspace/${TESTNET_CHANNEL}/logs/${name}___${ip}/sn_node__latest.log &
done
wait

echo "Logs updating..."