#!/bin/bash

# https://betterdev.blog/minimal-safe-bash-script-template/
set -Eeuo pipefail
trap cleanup SIGINT SIGTERM ERR EXIT

TESTNET_CHANNEL=$(terraform workspace show)

script_dir=$(cd "$(dirname "${BASH_SOURCE[0]}")" &>/dev/null && pwd -P)

cleanup() {
  trap - SIGINT SIGTERM ERR EXIT
  # script cleanup here
}

# rm -rf logs/${TESTNET_CHANNEL}/* || true

mkdir -p logs/${TESTNET_CHANNEL}
cat ${TESTNET_CHANNEL}-ip-list | while read line; do
  ip=$(echo $line | awk '{print $2}')
  name=$(echo $line | awk '{print $1}')
  rsync -P root@${ip}:~/logs/sn_node.log logs/${TESTNET_CHANNEL}/sn_node.log
done
wait

echo "Logs updated"

cleanup