#!/bin/bash

# https://betterdev.blog/minimal-safe-bash-script-template/
set -Eeuo pipefail
trap cleanup SIGINT SIGTERM ERR EXIT

TESTNET_CHANNEL=$(terraform workspace show)

script_dir=$(cd "$(dirname "${BASH_SOURCE[0]}")" &>/dev/null && pwd -P)

cleanup() {
  trap - SIGINT SIGTERM ERR EXIT
  # script cleanup here
}

mkdir -p logs/${TESTNET_CHANNEL}

cat ${TESTNET_CHANNEL}-ip-list | while read line; do
  name=$(echo $line | awk '{print $1}')
  ip=$(echo $line | awk '{print $2}')
  echo "Getting $name logs from $ip"
  rsync -r root@${ip}:~/logs logs/${TESTNET_CHANNEL}/${name}___${ip} &
done
wait

echo "Logs updated"

cleanup
