#!/bin/bash

# https://betterdev.blog/minimal-safe-bash-script-template/
set -Eeuo pipefail
trap cleanup SIGINT SIGTERM ERR EXIT

script_dir=$(cd "$(dirname "${BASH_SOURCE[0]}")" &>/dev/null && pwd -P)

cleanup() {
  trap - SIGINT SIGTERM ERR EXIT
  # script cleanup here
}

NODE_COUNT=${1:-11}
ELDER_COUNT=5
adult_count=$(($NODE_COUNT-$ELDER_COUNT))
# 2mb
TWO_MB=$(( 2 * 1024 * 1024 ))
node_capacity=${1:-$TWO_MB}

source "$script_dir/../src/droplet-operations"
source "$script_dir/../src/section-operations"

echo "Setting up Digital Ocean"
setup_doctl
echo "Digital Ocean setup complete"

create_elder_droplets
create_adult_droplets $adult_count 
echo "$NODE_COUNT Droplets created"
register_hosts
echo "Hosts registered"
download_node_binary_on_nodes
echo "Binary downloaded to all nodes"
deploy_elders $node_capacity
echo "elders started"
deploy_adults $node_capacity
echo "adults started"

cleanup

