#!/bin/bash

# To be used to start a bytehound server on a given node...
# Needs bytehound to be installed there, which is as yet, not working
set -e

# https://betterdev.blog/minimal-safe-bash-script-template/
set -Eeuo pipefail
trap cleanup SIGINT SIGTERM ERR EXIT
#

TARGERT_NODE_IP=${1}

if [[ -z "${TARGERT_NODE_IP}" ]]; then
    echo "The TARGERT_NODE_IP arg must be set with your personal access token."
    exit 1
fi

cleanup() {
  trap - SIGINT SIGTERM ERR EXIT
  # script cleanup here
}

echo "starting mem profile server on $1"
ssh root@${1} "nohup ./bytehound server -i ${1} memory-profiling_*.dat &"

open "http://${1}:8080"


cleanup