#!/bin/bash

## This script starts a node on a remote machine to join an existing section.
## It requires the connection information to be passed to it.

# Required arguments

# Hard coded contacts
hard_coded_contacts=$1
# Node data path
data_path=$2

# 2mb
TWO_MB=$(( 2 * 1024 * 1024 ))
#  Node capacity
MAX_CAPACITY=${3:-$TWO_MB}


if [ -d "$data_path" ]; then 
    rm -rf $data_path/*;
else
    mkdir -p ${data_path}
fi


export RUST_LOG=sn_node=trace
export RUST_BACKTRACE=1

echo "Starting node w/ capacity $MAX_CAPACITY"
echo "./sn_node --max-capacity \"${MAX_CAPACITY}\" --root-dir ${data_path} --hard-coded-contacts ${hard_coded_contacts} -vvvvv &> ${data_path}/node.stdout &"

chmod +x sn_node 
./sn_node --max-capacity $MAX_CAPACITY --root-dir ${data_path} --hard-coded-contacts ${hard_coded_contacts} -vvvvv &> ${data_path}/node.stdout &