#!/bin/bash

## This script starts a node on a remote machine to join an existing section.
## It requires the connection information to be passed to it.

# Required arguments

# Hard coded contacts
hcc=$1
# Node data path
data_path=$2

# 2mb
2MB = $(( 2 * 1024 * 1024 ))
#  Node capacity
max_capacity=${3:-$2MB}


if [ -d "$data_path" ]; then 
    rm -rf $data_path/*;
else
    mkdir -p ${data_path}
fi


export RUST_LOG=sn_node=trace
export RUST_BACKTRACE=1

chmod +x sn_node
./sn_node --max-capacity ${max-capacity} --root-dir ${data_path} --hard-coded-contacts ${hcc} -vvvvv &> ${data_path}/node.stdout &